name: Versioning

on:
  push:
    branches: [main]

env:
  NX_BRANCH: ${GITHUB_REF##*/}

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint Apps
        run: npm run nx affected:lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}  --parallel --maxParallel=3

      - name: Test Apps
        run: npm run nx affected:test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}  --parallel --maxParallel=3

      - name: e2e Apps
        run: npm run nx affected:e2e --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}  --parallel --maxParallel=3

      - name: Build Apps
        run: npm run nx affected:build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD  }}  --parallel --maxParallel=3

      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: echo new tag
        run: |
          echo "${{ steps.taggerDryRun.outputs.new_tag }}"

      - name: echo tag
        run: |
          echo "${{ steps.taggerDryRun.outputs.tag }}"

      - name: echo part
        run: |
          echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"
